/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        // Neon colors
        neon: {
          pink: 'var(--neon-pink)',
          cyan: 'var(--neon-cyan)',
          purple: 'var(--neon-purple)',
          green: 'var(--neon-green)',
          orange: 'var(--neon-orange)',
          yellow: 'var(--neon-yellow)',
          blue: 'var(--neon-blue)',
        },
        // Theme colors
        primary: 'var(--color-primary)',
        'primary-hover': 'var(--color-primary-hover)',
        'primary-light': 'var(--color-primary-light)',
        secondary: 'var(--color-secondary)',
        accent: 'var(--color-accent)',
        background: 'var(--color-background)',
        surface: 'var(--color-surface)',
        'surface-solid': 'var(--color-surface-solid)',
        'surface-hover': 'var(--color-surface-hover)',
        'surface-alt': 'var(--color-surface-alt)',
        glass: 'var(--color-glass)',
        'glass-border': 'var(--color-glass-border)',
        border: 'var(--color-border)',
        'border-light': 'var(--color-border-light)',
        'border-neon': 'var(--color-border-neon)',
        'border-accent': 'var(--color-border-accent)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-tertiary': 'var(--color-text-tertiary)',
        'text-inverse': 'var(--color-text-inverse)',
        'text-neon': 'var(--color-text-neon)',
        link: 'var(--color-link)',
        'link-hover': 'var(--color-link-hover)',
        success: 'var(--color-success)',
        warning: 'var(--color-warning)',
        error: 'var(--color-error)',
        info: 'var(--color-info)',
        vip: 'var(--color-vip)',
        'vip-bg': 'var(--color-vip-bg)',
        'new-badge': 'var(--color-new-badge)',
        'new-badge-text': 'var(--color-new-badge-text)',
        salary: 'var(--color-salary)',
        'salary-text': 'var(--color-salary-text)',
        remote: 'var(--color-remote)',
        facebook: 'var(--color-facebook)',
        telegram: 'var(--color-telegram)',
        whatsapp: 'var(--color-whatsapp)',
        linkedin: 'var(--color-linkedin)',
        copy: 'var(--color-copy)',
        'table-bg': 'var(--color-table-bg)',
        'table-header-bg': 'var(--color-table-header-bg)',
        'table-row-hover': 'var(--color-table-row-hover)',
        'table-border': 'var(--color-table-border)',
        'table-border-outer': 'var(--color-table-border-outer)',
      },
      fontFamily: {
        display: ['Orbitron', 'Rajdhani', 'sans-serif'],
        heading: ['Rajdhani', 'Orbitron', 'sans-serif'],
        sans: ['Inter', 'Noto Sans Georgian', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        'neon-cyan': 'var(--shadow-neon-cyan)',
        'neon-pink': 'var(--shadow-neon-pink)',
        'neon-purple': 'var(--shadow-neon-purple)',
        'glow': '0 0 20px currentColor',
        'glow-lg': '0 0 40px currentColor',
      },
      backgroundImage: {
        'gradient-neon': 'var(--gradient-neon)',
        'gradient-cyber': 'var(--gradient-cyber)',
        'gradient-aurora': 'var(--gradient-aurora)',
        'gradient-sunset': 'var(--gradient-sunset)',
        'gradient-matrix': 'var(--gradient-matrix)',
      },
      animation: {
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
        'neon-flicker': 'neon-flicker 1.5s infinite',
        'border-flow': 'border-flow 4s ease infinite',
        'float': 'float 3s ease-in-out infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'glow-pulse': 'glow-pulse 2s ease-in-out infinite',
        'scan-line': 'scan-line 8s linear infinite',
        'rotate-gradient': 'rotate-gradient 3s linear infinite',
      },
      keyframes: {
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 20px var(--neon-cyan-glow)' },
          '50%': { boxShadow: '0 0 40px var(--neon-cyan-glow), 0 0 60px rgba(0, 245, 255, 0.4)' },
        },
        'border-flow': {
          '0%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
          '100%': { backgroundPosition: '0% 50%' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'shimmer': {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
      backdropBlur: {
        'glass': '20px',
        'heavy': '40px',
      },
      borderRadius: {
        'cyber': '2px 16px 2px 16px',
      },
    },
  },
  plugins: [],
};
