/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        'primary-hover': 'var(--color-primary-hover)',
        'primary-light': 'var(--color-primary-light)',
        secondary: 'var(--color-secondary)',
        background: 'var(--color-background)',
        surface: 'var(--color-surface)',
        'surface-hover': 'var(--color-surface-hover)',
        'surface-alt': 'var(--color-surface-alt)',
        border: 'var(--color-border)',
        'border-light': 'var(--color-border-light)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-tertiary': 'var(--color-text-tertiary)',
        'text-inverse': 'var(--color-text-inverse)',
        link: 'var(--color-link)',
        'link-hover': 'var(--color-link-hover)',
        success: 'var(--color-success)',
        warning: 'var(--color-warning)',
        error: 'var(--color-error)',
        info: 'var(--color-info)',
        vip: 'var(--color-vip)',
        'vip-bg': 'var(--color-vip-bg)',
        'new-badge': 'var(--color-new-badge)',
        'new-badge-text': 'var(--color-new-badge-text)',
        salary: 'var(--color-salary)',
        'salary-text': 'var(--color-salary-text)',
        remote: 'var(--color-remote)',
        facebook: 'var(--color-facebook)',
        telegram: 'var(--color-telegram)',
        whatsapp: 'var(--color-whatsapp)',
        linkedin: 'var(--color-linkedin)',
        copy: 'var(--color-copy)',
        'table-bg': 'var(--color-table-bg)',
        'table-header-bg': 'var(--color-table-header-bg)',
        'table-row-hover': 'var(--color-table-row-hover)',
        'table-border': 'var(--color-table-border)',
        'table-border-outer': 'var(--color-table-border-outer)',
      },
      fontFamily: {
        sans: ['Arial', 'Noto Sans Georgian', 'system-ui', 'sans-serif'],
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
      },
    },
  },
  plugins: [],
};
