"""Reporting and cleanup tasks."""
from datetime import datetime, timedelta
import aiosmtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

from sqlalchemy import text

from app.core.config import settings
from app.core.logging import get_logger
from app.core.database import get_db_session
from app.services.queue_service import QueueService

logger = get_logger(__name__)


async def send_daily_report() -> None:
    """Send daily summary report via email."""
    logger.info("generating_daily_report")

    session = await get_db_session()
    try:
        # Get statistics for today
        today = datetime.utcnow().date()
        yesterday = today - timedelta(days=1)

        # Messages sent today
        sent_today_query = text("""
            SELECT COUNT(*)
            FROM channel_message_history
            WHERE status = 'sent'
              AND DATE(sent_at) = :today
        """)
        result = await session.execute(sent_today_query, {"today": today})
        sent_today = result.scalar() or 0

        # Messages failed today
        failed_today_query = text("""
            SELECT COUNT(*)
            FROM channel_message_history
            WHERE status = 'failed'
              AND DATE(created_at) = :today
        """)
        result = await session.execute(failed_today_query, {"today": today})
        failed_today = result.scalar() or 0

        # Pending in queue
        pending_query = text("""
            SELECT COUNT(*)
            FROM channel_message_queue
            WHERE status = 'pending'
        """)
        result = await session.execute(pending_query)
        pending_count = result.scalar() or 0

        # Total sent all time
        total_sent_query = text("""
            SELECT COUNT(*)
            FROM channel_message_history
            WHERE status = 'sent'
        """)
        result = await session.execute(total_sent_query)
        total_sent = result.scalar() or 0

        # Jobs not yet posted
        not_posted_query = text("""
            SELECT COUNT(*)
            FROM jobs j
            WHERE j.status = 'active'
              AND NOT EXISTS (
                  SELECT 1 FROM channel_message_history h
                  WHERE h.job_id = j.id AND h.status = 'sent'
              )
        """)
        result = await session.execute(not_posted_query)
        not_posted = result.scalar() or 0

        # Build report
        report_html = f"""
        <html>
        <body>
        <h2>Channel Sender Daily Report - {today}</h2>

        <h3>Today's Activity</h3>
        <ul>
            <li><strong>Messages Sent:</strong> {sent_today}</li>
            <li><strong>Messages Failed:</strong> {failed_today}</li>
        </ul>

        <h3>Queue Status</h3>
        <ul>
            <li><strong>Pending:</strong> {pending_count}</li>
            <li><strong>Jobs Not Yet Posted:</strong> {not_posted}</li>
        </ul>

        <h3>All Time</h3>
        <ul>
            <li><strong>Total Messages Sent:</strong> {total_sent}</li>
        </ul>

        <hr>
        <p><small>Generated by Channel Sender Service at {datetime.utcnow().isoformat()}</small></p>
        </body>
        </html>
        """

        # Send email
        await send_email(
            to=settings.REPORT_EMAIL_TO,
            subject=f"Channel Sender Report - {today}",
            html_content=report_html,
        )

        logger.info(
            "daily_report_sent",
            sent_today=sent_today,
            failed_today=failed_today,
            pending=pending_count,
        )

    except Exception as e:
        logger.exception("daily_report_error", error=str(e))
    finally:
        await session.close()


async def send_email(to: str, subject: str, html_content: str) -> None:
    """Send an email via SMTP."""
    message = MIMEMultipart("alternative")
    message["Subject"] = subject
    message["From"] = settings.SMTP_FROM
    message["To"] = to

    html_part = MIMEText(html_content, "html")
    message.attach(html_part)

    try:
        await aiosmtplib.send(
            message,
            hostname=settings.SMTP_HOST,
            port=settings.SMTP_PORT,
            start_tls=False,  # Mailpit doesn't need TLS
        )
        logger.info("email_sent", to=to, subject=subject)
    except Exception as e:
        logger.error("email_send_failed", to=to, error=str(e))
        raise


async def cleanup_old_entries() -> int:
    """Remove old entries from queue and history tables.

    - Removes cancelled queue entries older than 7 days
    - Removes sent queue entries older than 30 days

    Returns number of entries removed.
    """
    logger.info("cleanup_started")

    session = await get_db_session()
    try:
        queue_service = QueueService(session)

        # Clean up old queue entries (30 days)
        deleted = await queue_service.cleanup_old_entries(days=30)

        await session.commit()

        logger.info("cleanup_completed", deleted_count=deleted)
        return deleted

    except Exception as e:
        await session.rollback()
        logger.exception("cleanup_error", error=str(e))
        return 0
    finally:
        await session.close()
